AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  VideoArchiver

  Powertools for AWS Lambda (Python) example

Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 40
    MemorySize: 128
    Runtime: python3.8

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  PollSourcesFunction:
    Type: AWS::Serverless::Function     # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      Handler: app.lambda_handler
      CodeUri: lambda
      Description: Function to poll video sources using container task, and download them.
      Architectures:
      - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsHelloWorld
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python
  MainStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: stepfunction/ignore.asl


Outputs:
  PollSourcesFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt PollSourcesFunction.Arn

